// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVxRxmRU9YtPyQUD8qCviL9KqpAu_IXmc',
    appId: '1:1014874760309:web:bc8f0fbc749fbfd074c43c',
    messagingSenderId: '1014874760309',
    projectId: 'sophiaappfinanceiro',
    authDomain: 'sophiaappfinanceiro.firebaseapp.com',
    storageBucket: 'sophiaappfinanceiro.firebasestorage.app',
    measurementId: 'G-LZHW5TE0KX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFICqBd23lkSTKLCRRAHTxIKO08__jAJQ',
    appId: '1:1014874760309:android:4fad9b4b90ce5f8174c43c',
    messagingSenderId: '1014874760309',
    projectId: 'sophiaappfinanceiro',
    storageBucket: 'sophiaappfinanceiro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT_SL0IuMCApUjiJdo5kIiVu94xbuoqsM',
    appId: '1:1014874760309:ios:bc3d6b110a2bf39774c43c',
    messagingSenderId: '1014874760309',
    projectId: 'sophiaappfinanceiro',
    storageBucket: 'sophiaappfinanceiro.firebasestorage.app',
    iosBundleId: 'com.example.financeProjectSophiaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT_SL0IuMCApUjiJdo5kIiVu94xbuoqsM',
    appId: '1:1014874760309:ios:bc3d6b110a2bf39774c43c',
    messagingSenderId: '1014874760309',
    projectId: 'sophiaappfinanceiro',
    storageBucket: 'sophiaappfinanceiro.firebasestorage.app',
    iosBundleId: 'com.example.financeProjectSophiaFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVxRxmRU9YtPyQUD8qCviL9KqpAu_IXmc',
    appId: '1:1014874760309:web:f70b90712ca25aa874c43c',
    messagingSenderId: '1014874760309',
    projectId: 'sophiaappfinanceiro',
    authDomain: 'sophiaappfinanceiro.firebaseapp.com',
    storageBucket: 'sophiaappfinanceiro.firebasestorage.app',
    measurementId: 'G-2GN41JEW7Q',
  );
}
