const List<Map<String, dynamic>> sampleTransactions = [
  {
    'userId': '3lkndaqqqf3',
    'description': 'Salário',
    'amount': 3000.0,
    'date': '2021-10-10',
    'type': 'income',
    'category': 'Salário',
    'paymentMethod': 'Transferencia Bancária',
  },
  {
    'userId': '3lkndaqqqf3',
    'description': 'Compra no supermercado',
    'amount': 50.0,
    'date': '2024-10-10',
    'type': 'expense',
    'category': 'Supermercado',
    'paymentMethod': 'Cartão de Crédito',
  },
  {
    'userId': '3lkrtfgcdf3',
    'description': 'Pagamento de aluguel',
    'amount': 500.0,
    'date': '2024-10-10',
    'type': 'expense',
    'category': 'Aluguel',
    'paymentMethod': 'Boleto',
  },
  {
    'userId': '3lkndxfcvdf3',
    'description': 'Compra de eletrônicos',
    'amount': 300.0,
    'date': '2024-10-10',
    'type': 'expense',
    'category': 'Eletrônicos',
    'paymentMethod': 'Cartão de Crédito',
  },
  {
    'userId': '3lkndaqqqf3',
    'description': 'Freelance',
    'amount': 800.0,
    'date': '2025-10-10',
    'type': 'income',
    'category': 'Freelance',
    'paymentMethod': 'Salario',
  },
];
